version: '3'

volumes:
  db:

services:

  mongo_db:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
      MONGO_INITDB_DATABASE: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo_db

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME:
#      ME_CONFIG_MONGODB_ADMINPASSWORD:

